name: 'CI'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: GeeWizWow/acc_lap_viewer_thing:latest

